using UnityEngine;
using UnityEngine.UI;
public class PhotoGalleryUI : MonoBehaviour
{
    [Header("UI References")]
    [SerializeField] private Transform photoContainer;     // –ö–æ–Ω—Ç–µ–π–Ω–µ—Ä –ø–æ–¥ —Ñ–æ—Ç–∫–∏ (Content)
    [SerializeField] private GameObject visual;     // –ö–æ–Ω—Ç–µ–π–Ω–µ—Ä –ø–æ–¥ —Ñ–æ—Ç–∫–∏ (Content)
    [SerializeField] private GameObject photoItemPrefab;   // –ü—Ä–µ—Ñ–∞–± –æ–¥–Ω–æ–≥–æ —ç–ª–µ–º–µ–Ω—Ç–∞ –≥–∞–ª–µ—Ä–µ–∏
    
    [Header("Source")]
    [SerializeField] private PhotoStorage photoStorage;
    

    private void Update()
    {
        //–í—Ä–µ–º–µ–Ω–Ω–æ
        if (Input.GetKeyDown(KeyCode.G))
        {
            visual.SetActive(true);
        }
        if (Input.GetKeyDown(KeyCode.H))
        {
            visual.SetActive(false);
        }
        
    }

    public void AddLastPhotoToGallery()
    {
        
        if (photoStorage.CurrentPhotos == 0)
        {
            Debug.LogWarning("[PhotoGalleryUI] –ù–µ—Ç —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏–π –¥–ª—è –¥–æ–±–∞–≤–ª–µ–Ω–∏—è.");
            return;
        }

        Texture2D photo = photoStorage.GetPhoto(photoStorage.CurrentPhotos - 1);
        if (photo == null)
        {
            Debug.LogWarning("[PhotoGalleryUI] –ü–æ—Å–ª–µ–¥–Ω—è—è —Ñ–æ—Ç–æ–≥—Ä–∞—Ñ–∏—è –Ω–µ–¥–æ—Å—Ç—É–ø–Ω–∞.");
            return;
        }

        GameObject photoItem = Instantiate(photoItemPrefab, photoContainer);
        Image image = photoItem.GetComponentInChildren<Image>();
        if (image == null)
        {
            Debug.LogError("[PhotoGalleryUI] –ü—Ä–µ—Ñ–∞–± –Ω–µ —Å–æ–¥–µ—Ä–∂–∏—Ç –∫–æ–º–ø–æ–Ω–µ–Ω—Ç Image.");
            return;
        }

        Sprite sprite = Sprite.Create(photo, new Rect(0, 0, photo.width, photo.height), new Vector2(0.5f, 0.5f), 100f);
        image.sprite = sprite;

        Debug.Log("[PhotoGalleryUI] üñºÔ∏è –§–æ—Ç–æ–≥—Ä–∞—Ñ–∏—è –¥–æ–±–∞–≤–ª–µ–Ω–∞ –≤ –≥–∞–ª–µ—Ä–µ—é.");
    }
}
